
# Create this anaconda environment using the following command:
#   conda env create -f doc_environment.yml

name: doc_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - sphinx-autoapi
  - myst-parser
  - sphinx_rtd_theme
