name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up test environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: test_environment.yml
        activate-environment: test_env
    - name: Run tests
      shell: bash -l {0}
      run: |
        nosetests -v --nocapture
